### PR TITLE
lang ja: NextOn

### PR DESCRIPTION
**Pull request by Narazaka**
In Japanese 「次へ」 means "Play next video". I think 「再生中」 that is "playing" is suitable for this situation.

related: https://github.com/JLChnToZ/VVMW/issues/14#issuecomment-1763325100

### CODE REVIEW

**Comment by JLChnToZ** [comment]
This one is complicated, I don't think it should labelled as "playing". When it is in queue list of separated controls, it will be at the top of upcoming next, not current playing one.

**Comment by Narazaka** [comment]
hmm... but "Play next video" is very confused.
In English, is "Next On" a word that is comfortable whether the video is playing or the next thing that will play?

**Comment by JLChnToZ** [comment]
"Next on" does mean upcoming, and somewhat related to current playing one.
I think in the future I should separate it into 2 language keys, but in the mean while, a word equivalent of "upcoming" is the best fit to this language key.

**Comment by Narazaka** [comment]
Maybe 「次」 is still confused but somewhat better.

**Comment by JLChnToZ** [comment]
I'm not good at Japanese, so I trust you.

**Pull request merged**
