### PR TITLE
Update lang.json

### PR DESCRIPTION
**Pull request by Krislyz**
Added Hebrew (he-IL) version.

### CODE REVIEW

**Comment by JLChnToZ** [comment]
Sorry, I think I will on hold adding new languages at the moment, because I don't think there's enough UI space to select more languages (which requires redesign the layout), also it would be hard to maintain while new features with extra language keys are currently in development. (You still can use it in your own installation though.)

**Comment by JLChnToZ** [comment]
Hello, we are having plan to support more languages now, would you mind I re-open this pull request and merge your commit? (Even though it is quite some time and more language keys may added)

**Comment by Krislyz** [comment]
> Hello, we are having plan to support more languages now, would you mind I re-open this pull request and merge your commit? (Even though it is quite some time and more language keys may added)

Yeah of course

**Comment by JLChnToZ** [comment]
It is still closed and I can't reopen it, I think you can make it a new pull request, thank you very much.

**Comment by Krislyz** [comment]
> It is still closed and I can't reopen it, I think you can make it a new pull request, thank you very much.

I will check the file to make sure it's alright and will reopen the issue.

**Comment by JLChnToZ** [comment]
OK, thank you very much!
In current state the language json already contains Hebrew translation (which I uses AI to generate it), but I will say it would be better if someone could proof-read it or even have accurate localization by someone who actually speaks that language.

**Pull request closed without merging**
